module.exports = {
    3: {'type': 'o',
        'in': 2,
        'out': 1},
    4: {'type': 'c',
        'in': 2,
        'out': 1},
    5: {'type': 'h',
        'in': 2,
        'out': 1},
    6: {'type': 't',
        'in': 1,
        'out': 1},
    7: {'type': 'o',
        'in': 3,
        'out': 2},
    8: {'type': 'c',
        'in': 3,
        'out': 2},
    9: {'type': 'o',
        'in': 1,
        'out': 1},
    10: {'type': 'c',
        'in': 2,
        'out': 2},
    11: {'type': 'u',
        'in': 1,
        'out': 2},
    12: {'type': 'h',
        'in': 2,
        'out': 2},
    13: {'type': 'r',
        'in': 0,
        'out': 1},
    14: {'type': 't',
        'in': 2,
        'out': 2},
    15: {'type': 'c',
        'in': 2,
        'out': 3},
    16: {'type': 'o',
        'in': 2,
        'out': 3},
    17: {'type': 'u',
        'in': 1,
        'out': 2},
    18: {'type': 'r',
        'in': 0,
        'out': 2},
    19: {'type': 't',
        'in': 2,
        'out': 3},
    20: {'type': 'c',
        'in': 3,
        'out': 5},
    21: {'type': 'h',
        'in': 2,
        'out': 4},
    22: {'type': 'r',
        'in': 0,
        'out': 2},
    23: {'type': 'u',
        'in': 1,
        'out': 3},
    24: {'type': 't',
        'in': 2,
        'out': 4},
    25: {'type': 'c',
        'in': 2,
        'out': 5},
    26: {'type': 'o',
        'in': 2,
        'out': 5},
    27: {'type': 'r',
        'in': 0,
        'out': 3},
    28: {'type': 'u',
        'in': 1,
        'out': 4},
    29: {'type': 'h',
        'in': 1,
        'out': 4},
    30: {'type': 't',
        'in': 3,
        'out': 6},
    31: {'type': 'c',
        'in': 3,
        'out': 6},
    32: {'type': 'o',
        'in': 3,
        'out': 6},
    33: {'type': 'r',
        'in': 0,
        'out': 4},
    34: {'type': 'u',
        'in': 1,
        'out': 5},
    35: {'type': 'o',
        'in': 1,
        'out': 5},
    36: {'type': 'c',
        'in': 3,
        'out': 7},
    37: {'type': 'r',
        'in': 0,
        'out': 4},
    38: {'type': 't',
        'in': 3,
        'out': 7},
    39: {'type': 'u',
        'in': 1,
        'out': 6},
    40: {'type': 'o',
        'in': 2,
        'out': 6},
    42: {'type': 'c',
        'in': 2,
        'out': 6},
    44: {'type': 'r',
        'in': 0,
        'out': 5},
    46: {'type': 'h',
        'in': 3,
        'out': 7},
    50: {'type': 'r',
        'in': 0,
        'out': 6}
}
