const plants = {
    3: {'type': 'o',
        'in': 2,
        'out': 1},
    4: {'type': 'c',
        'in': 2,
        'out': 1},
    5: {'type': 'h',
        'in': 2,
        'out': 1},
    6: {'type': 't',
        'in': 1,
        'out': 1},
    7: {'type': 'o',
        'in': 3,
        'out': 2},
    8: {'type': 'c',
        'in': 3,
        'out': 2},
    9: {'type': 'o',
        'in': 1,
        'out': 1},
    10: {'type': 'c',
        'in': 2,
        'out': 2},
    11: {'type': 'u',
        'in': 1,
        'out': 2},
    12: {'type': 'h',
        'in': 2,
        'out': 2},
    13: {'type': 'r',
        'in': 0,
        'out': 1},
    14: {'type': 't',
        'in': 2,
        'out': 2},
    15: {'type': 'c',
        'in': 2,
        'out': 3}
}